exp:
    experiment_dir: /home/cocochamba/Python_labs/genai_food101_repo
    device: cpu
    seed: 1987
    use_wandb: True
    model_type: diffusion

data:
    input_train_dir: data/train # /home/cocochamba/Python_labs/genai_food101_repo/
    input_val_dir: data/test # /home/cocochamba/Python_labs/genai_food101_repo/
    train_batch_size: 16
    val_batch_size: 16
    num_workers: 6
    
train:
    trainer: base_diffusion_trainer
    model: ddpm
    optimizer: adam
    checkpoint_path: /home/cocochamba/Python_labs/genai_food101_repo/checkpoints
    val_metrics: ["fid"]
    start_step: 0
    steps: 63000
    log_step: 200
    checkpoint_step: 500
    val_step: 500

checkpoint:
    start_step: 0
    run_id: 

utils:
    diffusion:
        n_timesteps: 500
        beta_min: 0.0001
        beta_max: 0.02
        
model_args:
    encoder_args:
        input_channels: 3
        time_embedding: 256
    decoder_args:
        last_fmap_channels: 512
        output_channels: 3
        time_embedding: 256
        first_fmap_channels: 64

optimizer_args:
    adam:
        lr: 0.001
        weight_decay: 0.0
    scheduler:
        T_max: 105
        eta_min: 0.00001


fid_args:
    batch_size: 8
    device: cuda
    dims: 2048

losses_coef:
    mse: 0.5
    smooth_l1: 0.5

losses_args:
    mse:
        reduction: mean
    smooth_l1:
        reduction: mean
        beta: 0.5